# Generated by Django 4.1.7 on 2023-06-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_autocall_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='callhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Contact', models.BigIntegerField(default='')),
                ('Status', models.CharField(default='', max_length=20)),
                ('Callduration', models.IntegerField(default='')),
            ],
        ),
    ]
