# Generated by Django 4.1.7 on 2023-06-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_callhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='callhistory',
            name='Recording_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
