# Generated by Django 4.1.7 on 2023-06-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_callhistory_recording_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callhistory',
            name='Callduration',
            field=models.CharField(default='', max_length=30),
        ),
    ]
