# Generated by Django 4.1.7 on 2023-07-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_kumuthan_role_kumuthan_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kumuthan_users',
            old_name='role',
            new_name='role_id',
        ),
    ]
