# Generated by Django 4.2.3 on 2023-07-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_role_kumuthan_users_role_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='autocall',
        ),
        migrations.DeleteModel(
            name='callhistory',
        ),
        migrations.RenameField(
            model_name='kumuthan_users',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='kumuthan_users',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
